version: '3.9'
services:

  apptest:
    image: node:21.0.0
    container_name: apptest
    user: "node"
    restart: always
    working_dir: /app
    ports:
      - '${APP_PORT:-3001}:3000'
    networks:
      - network-appTest
    volumes:
      - ./:/app
    command: bash -c "npm install ; npm run migration:run; npm run seed; npm run dev"
    depends_on:
      - db-postgres

  db-postgres:
    image: 'postgres:17.0'
    container_name: appTest_postgres
    environment:
      POSTGRES_ROOT_PASSWORD: 'postgres'
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - network-appTest
    volumes:
      - ./postgres/dbdata:/var/lib/postgres
    ports:
      - '${APP_PORT:-5432}:5432'
    security_opt:
      - seccomp:unconfined

networks:
  network-appTest:
    driver: bridge
